name: Build makedeb
on: {"pull_request"}
env: {"DEBIAN_FRONTEND": "noninteractive"}
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: proget.hunterwittenborn.com/docker/makedeb/makedeb-alpha:ubuntu-focal
      options: --user makedeb
    steps:
      - name: Install CI prerequisites
        run: sudo -E apt-get install git -y

      - name: Ensure directory permissions are correct
        run: sudo chown 'makedeb:makedeb' ../ "${HOME}" -R

      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Install needed dependencies
        working-directory: ./makedeb
        run: .drone/scripts/install-deps.sh
      
      - name: Run unit tests
        working-directory: ./makedeb
        run: release_type="${GITHUB_BASE_REF}" .drone/scripts/run-unit-tests.sh

# vim: expandtab ts=2 sw=2
